USERS_DB = "users/users.csv"
GRAPH_DB = "users/graph.json"
CHATS_DB = "chats/chats_id.csv"
POSTS_DB = "posts/post.csv"
TEMP_DB = "users/temp.csv"
REPLYES_DB = "posts/replyes.csv"
HASH_DB = "users/hashkeys.csv"